name: main
on: 
  push:
  schedule: # 计划任务触发
    - cron:  '05 16 * * *'
  watch:
    types: started    #手动点亮star则执行
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: "5.1.4"
        
    - uses: leafo/gh-actions-luarocks@v4
    - name: 安装模块 
      run: |
             luarocks install luasocket
              luarocks install md5
              luarocks install dkjson
               luarocks install luafilesystem
               luarocks install environ
        
    - name: 签到
      run: |
             lua ./hlxSignin.lua
             lua ./jzkjSignin.lua
      env:
        
            token: ${{ secrets.token }}
            hlxk: ${{ secrets.hlxk }}
            jzkjk: ${{ secrets.jzkjk }}
            
           
